Repository honeycombio/beeline-java, pull requests merged in 2022-03, with the labels that each got.

#187 Add support for Environment & Services
  beeline-core/src/main/java/io/honeycomb/beeline/DefaultBeeline.java
  beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
  beeline-core/src/main/java/io/honeycomb/beeline/tracing/Beeline.java
  beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracing.java
  beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java
  beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
  beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java
  beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodecTest.java
  beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodecTest.java
Labels: type: enhancement, version: bump major

#188 feat: add service.name field in addition to service_name
  beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanPostProcessor.java
  beeline-core/src/main/java/io/honeycomb/beeline/tracing/utils/TraceFieldConstants.java
  beeline-core/src/test/java/io/honeycomb/beeline/tracing/SendingSpanTest.java
  beeline-core/src/test/java/io/honeycomb/beeline/tracing/SpanPostProcessorTest.java
  beeline-core/src/test/java/io/honeycomb/beeline/tracing/TracerTest.java
Labels: type: enhancement, version: bump minor

#190 fix circular dependency for spring boot 2.6.x
  CONTRIBUTORS
  beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
  beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineConfig.java
Labels: type: bug, version: bump patch

#191 fix circular dependency for spring boot 2.6.x (#190)
  CONTRIBUTORS
  beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
  beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineConfig.java
Labels: type: bug, version: bump patch

#189 fix: only trim service name for dataset
  beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
  beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java
Labels: type: bug, version: bump minor

#197 maint: add basic example using DefaultBeeline
  examples/pom.xml
  examples/src/main/java/io/honeycomb/HelloWorld.java
  examples/src/main/java/io/honeycomb/HelloWorldClassic.java
  pom.xml
Labels: type: maintenance, version: no bump
