Repository honeycombio/beeline-java, pull requests merged in 2024-03, with the labels that each got.

#311 feat: support classic ingest keys
  beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
  beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java
  pom.xml
Labels: dependencies, version: bump minor

#313 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog

#312 rel: Prepare v2.2.0 release
  CHANGELOG.md
  beeline-core/pom.xml
  beeline-spring-boot-sleuth-starter/pom.xml
  beeline-spring-boot-starter/pom.xml
  examples/pom.xml
  pom.xml
Labels: type: maintenance, no-changelog
